[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"
]

# Fork testing configuration
[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/demo"

# Test configuration
[profile.default.fuzz]
runs = 256

[profile.default.invariant]
runs = 256
depth = 15

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
